In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('dataset.csv')

In [3]:
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [4]:
movies.describe()

                  id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

In [6]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

# Feature Selection

In [7]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [8]:
movies = movies[['id', 'title', 'genre', 'vote_average', 'release_date', 'overview']]

In [9]:
movies

,id,title,genre,vote_average,release_date,overview
0,278,The Shawshank Redemption,"Drama,Crime",8.7,1994-09-23,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",8.7,1995-10-19,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime",8.7,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",8.6,1993-12-15,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",8.6,1974-12-20,In the continuing saga of the Corleone crime f...
...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",4.7,2010-06-30,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",4.7,2015-07-22,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"Action,Science Fiction,War",4.6,1990-12-14,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",4.7,2007-11-29,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",4.6,2019-05-31,Seeking justice for his partner’s murder by an...

In [10]:
movies['tags'] = movies['genre']+movies['overview']

In [11]:
movies

,id,title,genre,vote_average,release_date,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",8.7,1994-09-23,Framed in the 1940s for the double murder of h...,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",8.7,1995-10-19,"Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime",8.7,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...","Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",8.6,1993-12-15,The true story of how businessman Oskar Schind...,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",8.6,1974-12-20,In the continuing saga of the Corleone crime f...,"Drama,CrimeIn the continuing saga of the Corle..."
...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",4.7,2010-06-30,"The story follows the adventures of Aang, a yo...","Action,Adventure,FantasyThe story follows the ..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",4.7,2015-07-22,The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,War",4.6,1990-12-14,"During World War II, a brave, patriotic Americ...","Action,Science Fiction,WarDuring World War II,..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",4.7,2007-11-29,A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,DramaA man named Farm..."
9999,455957,Domino,"Thriller,Action,Crime",4.6,2019-05-31,Seeking justice for his partner’s murder by an...,"Thriller,Action,CrimeSeeking justice for his p..."

In [12]:
new_data = movies.drop(columns = ['overview'])

In [13]:
new_data

,id,title,genre,vote_average,release_date,tags
0,278,The Shawshank Redemption,"Drama,Crime",8.7,1994-09-23,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",8.7,1995-10-19,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime",8.7,1972-03-14,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",8.6,1993-12-15,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",8.6,1974-12-20,"Drama,CrimeIn the continuing saga of the Corle..."
...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",4.7,2010-06-30,"Action,Adventure,FantasyThe story follows the ..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",4.7,2015-07-22,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,War",4.6,1990-12-14,"Action,Science Fiction,WarDuring World War II,..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",4.7,2007-11-29,"Adventure,Fantasy,Action,DramaA man named Farm..."
9999,455957,Domino,"Thriller,Action,Crime",4.6,2019-05-31,"Thriller,Action,CrimeSeeking justice for his p..."

# Data Transformation

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv = CountVectorizer(max_features=10000, stop_words='english')

In [16]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [17]:
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [18]:
vector.shape

(10000, 10000)

# Similarity

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
similarity = cosine_similarity(vector)

In [21]:
similarity

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])

In [22]:
new_data[new_data['title'] == "The Godfather"].index[0]

2

In [23]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10000 non-null  int64
 1   title         10000 non-null  object
 2   genre         9997 non-null   object
 3   vote_average  10000 non-null  float64
 4   release_date  10000 non-null  object
 5   tags          9985 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 468.9+ KB

In [24]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vector:vector[1])
for i in distance[1:5]:
    print(new_data.iloc[i[0]].title)
    print(new_data.iloc[i[0]].genre)
    print(new_data.iloc[i[0]].vote_average)
    print(new_data.iloc[i[0]].release_date)

The Godfather: Part II
Drama,Crime
8.6
1974-12-20
Felon
Action,Crime,Drama,Mystery
7.2
2008-07-17
House of Gucci
Drama,Crime,History
6.7
2021-11-24
Gotti
Crime,Drama,History,Thriller
5.3
2018-06-14

In [25]:
def recommend(movies):
    index = new_data[new_data['title'] == movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[1:5]:
        print(new_data.iloc[i[0]].title)
        print(new_data.iloc[i[0]].genre)
        print(new_data.iloc[i[0]].vote_average)
        print(new_data.iloc[i[0]].release_date)

In [26]:
recommend("The Shawshank Redemption")

Anything for Her
Drama,Thriller
6.9
2008-12-03
The Woodsman
Drama
6.9
2004-12-24
The Getaway
Action,Crime,Drama,Mystery,Romance,Thriller
5.6
1994-02-11
Pusher II
Crime,Drama,Thriller
7.2
2004-12-25

In [27]:
recommend("Dune")

The Day the Earth Stood Still
Drama,Science Fiction,Thriller
5.6
2008-12-10
Star Trek: Insurrection
Science Fiction,Action,Adventure,Thriller
6.4
1998-12-11
Star Trek V: The Final Frontier
Science Fiction,Action,Adventure,Thriller
5.8
1989-06-09
Doctor Who: The Time of the Doctor
Drama,Science Fiction,TV Movie
8.1
2013-12-25

In [28]:
import pickle

In [29]:
pickle.dump(new_data, open('movies_list.pkl', 'wb'))

In [30]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [31]:
pickle.load(open('movies_list.pkl', 'rb'))

,id,title,genre,vote_average,release_date,tags
0,278,The Shawshank Redemption,"Drama,Crime",8.7,1994-09-23,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",8.7,1995-10-19,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime",8.7,1972-03-14,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",8.6,1993-12-15,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",8.6,1974-12-20,"Drama,CrimeIn the continuing saga of the Corle..."
...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",4.7,2010-06-30,"Action,Adventure,FantasyThe story follows the ..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",4.7,2015-07-22,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,War",4.6,1990-12-14,"Action,Science Fiction,WarDuring World War II,..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",4.7,2007-11-29,"Adventure,Fantasy,Action,DramaA man named Farm..."
9999,455957,Domino,"Thriller,Action,Crime",4.6,2019-05-31,"Thriller,Action,CrimeSeeking justice for his p..."

In [32]:
pickle.load(open('similarity.pkl', 'rb'))

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])